baseURL = 'https://viivie.github.io/'
languageCode = 'zh-tw'
title = 'viivie 的貓窩'
theme = "hugo-theme-reimu"

[params]
  mainSections = ["posts"]

  # 瀏覽器分頁圖示 (Favicon)
  favicon = "static/favicon.ico"
  
  # 如果你想換掉主題裡的頭像
  # avatar = "/avatar.png"